<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="108281" started-at="2019-07-28T06:31:16Z" finished-at="2019-07-28T06:33:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="108281" started-at="2019-07-28T06:31:16Z" finished-at="2019-07-28T06:33:04Z">
      <class name="testScripts.TestScript2">
        <test-method status="PASS" signature="onewayFlightBooking(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript2@1593948d]" name="onewayFlightBooking" duration-ms="11898" started-at="2019-07-28T06:32:40Z" data-provider="getdata2" finished-at="2019-07-28T06:32:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Paris]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[First class]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onewayFlightBooking -->
        <test-method status="PASS" signature="onewayFlightBooking(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript2@1593948d]" name="onewayFlightBooking" duration-ms="12093" started-at="2019-07-28T06:32:52Z" data-provider="getdata2" finished-at="2019-07-28T06:33:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Frankfurt]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Business class]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onewayFlightBooking -->
      </class> <!-- testScripts.TestScript2 -->
      <class name="testScripts.TestScript1">
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="19293" started-at="2019-07-28T06:31:16Z" data-provider="getdata2" finished-at="2019-07-28T06:31:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[username6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password6]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sign-on:Mercury Tours]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testScripts.TestScript1.loginTest(TestScript1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="8621" started-at="2019-07-28T06:31:36Z" data-provider="getdata2" finished-at="2019-07-28T06:31:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[username7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sign-on:Mercury Tours]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testScripts.TestScript1.loginTest(TestScript1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="10356" started-at="2019-07-28T06:31:44Z" data-provider="getdata2" finished-at="2019-07-28T06:31:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[username8]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password8]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sign-on:Mercury Tours]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testScripts.TestScript1.loginTest(TestScript1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="8563" started-at="2019-07-28T06:31:55Z" data-provider="getdata2" finished-at="2019-07-28T06:32:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[username9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password9]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sign-on:Mercury Tours]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Sign-on:Mercury Tours] but found [Sign-on: Mercury Tours]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at testScripts.TestScript1.loginTest(TestScript1.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="11846" started-at="2019-07-28T06:32:03Z" data-provider="getdata2" finished-at="2019-07-28T06:32:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Find a Flight: Mercury Tours:]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="13140" started-at="2019-07-28T06:32:15Z" data-provider="getdata2" finished-at="2019-07-28T06:32:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Find a Flight: Mercury Tours:]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testScripts.TestScript1@482f8f11]" name="loginTest" duration-ms="11987" started-at="2019-07-28T06:32:28Z" data-provider="getdata2" finished-at="2019-07-28T06:32:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Find a Flight: Mercury Tours:]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- testScripts.TestScript1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
